/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 grips.glb -T -j -k 
Files: grips.glb [448.7KB] > /Users/joelmik/Code/kastenfabriek/public/objects/grips-transformed.glb [76.24KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/objects/grips-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Greep_Button" geometry={nodes.Greep_Button.geometry} material={nodes.Greep_Button.material} position={[-0.366, 0, 0]} scale={0.01} />
      <mesh name="Greep_T-classic" geometry={nodes['Greep_T-classic'].geometry} material={nodes['Greep_T-classic'].material} position={[-0.264, 0, 0]} scale={0.01} />
      <mesh name="Greep_Monument" geometry={nodes.Greep_Monument.geometry} material={nodes.Greep_Monument.material} position={[-0.207, 0, 0]} scale={0.01} />
      <mesh name="Greep_Loop" geometry={nodes.Greep_Loop.geometry} material={nodes.Greep_Loop.material} position={[-0.155, 0, 0]} scale={0.01} />
      <mesh name="Greep_Ribbel" geometry={nodes.Greep_Ribbel.geometry} material={nodes.Greep_Ribbel.material} position={[-0.474, 0, 0]} scale={0.01} />
      <mesh name="Greep_MiniPure" geometry={nodes.Greep_MiniPure.geometry} material={nodes.Greep_MiniPure.material} position={[-0.103, 0, 0]} scale={0.01} />
      <mesh name="Greep_Pure" geometry={nodes.Greep_Pure.geometry} material={nodes.Greep_Pure.material} position={[-0.061, 0, 0]} scale={0.01} />
      <mesh name="Greep_Olive" geometry={nodes.Greep_Olive.geometry} material={nodes.Greep_Olive.material} position={[-0.309, 0, 0]} scale={0.01} />
      <mesh name="Greep_T_Ribbel" geometry={nodes.Greep_T_Ribbel.geometry} material={nodes.Greep_T_Ribbel.material} position={[-0.518, 0, 0]} scale={0.01} />
      <mesh name="Greep_MiniBar" geometry={nodes.Greep_MiniBar.geometry} material={nodes.Greep_MiniBar.material} position={[-0.645, 0, 0]} scale={0.01} />
      <mesh name="Greep_Twin" geometry={nodes.Greep_Twin.geometry} material={nodes.Greep_Twin.material} position={[0.034, 0, 0]} scale={0.01} />
      <mesh name="Greep_Bar" geometry={nodes.Greep_Bar.geometry} material={nodes.Greep_Bar.material} position={[-0.604, 0, 0]} scale={0.01} />
      <mesh name="Greep_Pure_110" geometry={nodes.Greep_Pure_110.geometry} material={nodes.Greep_Pure_110.material} position={[-0.028, 0, 0]} scale={0.01} />
      <mesh name="Greep_Bar_120" geometry={nodes.Greep_Bar_120.geometry} material={nodes.Greep_Bar_120.material} position={[-0.559, 0, 0]} scale={0.01} />
      <mesh name="Greep_Tonton" geometry={nodes.Greep_Tonton.geometry} material={nodes.Greep_Tonton.material} position={[-0.42, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/objects/grips-transformed.glb')
