/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hinge-og.glb -T -j -k
Files: hinge-og.glb [33.6KB] > /Users/joelmik/Code/kastenfabriek/public/objects/hinge-og-transformed.glb [25.95KB] (23%)
*/

import { useRef, useEffect, useMemo } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three/webgpu'
import gsap from 'gsap'

export function Model({ doorsOpen = false, ...props }) {
  const group = useRef()
  const proxyRef = useRef({ t: 0 })
  const { nodes, materials, animations, scene } = useGLTF('/objects/hinge.glb')
  const { actions } = useAnimations(animations, group)

  // Center the hinge model at origin so position prop places it correctly
  const offset = useMemo(() => {
    const box = new THREE.Box3().setFromObject(scene)
    return box.getCenter(new THREE.Vector3()).negate()
  }, [scene])

  // Initialize: play once and immediately pause at t=0
  useEffect(() => {
    const action = Object.values(actions)[0]
    if (!action) return
    action.reset()
    action.play()
    action.paused = true
    action.time = 0
    proxyRef.current.t = 0
  }, [actions])

  // Animate action.time based on doorsOpen
  useEffect(() => {
    const action = Object.values(actions)[0]
    if (!action) return
    const duration = action.getClip().duration

    gsap.killTweensOf(proxyRef.current)
    gsap.to(proxyRef.current, {
      t: doorsOpen ? duration : 0,
      duration: 0.6,
      ease: 'power2.inOut',
      onUpdate: () => {
        action.time = Math.max(0, Math.min(duration, proxyRef.current.t))
      },
    })
  }, [doorsOpen, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[offset.x, offset.y, offset.z]}>
        <group name="Wardrobe_Elements">
          <group name="Armature_Scharnier1001" position={[0.026, 0.318, 0.577]} scale={0.014}>
            <group name="Bone003" position={[-1.066, 0, 0.456]} />
            <group name="Bone004" position={[-1.066, 0, 0.456]} />
            <group name="Bone001" position={[0.668, 0, 0.603]} rotation={[-Math.PI / 2, 0, 1.694]}>
              <group name="Bone002" position={[0, 1.409, 0]} rotation={[0, 0, -0.885]}>
                <group name="Bone005" position={[0, 0.463, 0]} rotation={[0, 0, -1.975]}>
                  <mesh name="As1_Scharnier1001" geometry={nodes.As1_Scharnier1001.geometry} material={nodes.As1_Scharnier1001.material} position={[0, 1.159, 0]} rotation={[Math.PI / 2, 1.167, 0]} scale={69.753} />
                </group>
                <mesh name="Deur_Scharnier1001" geometry={nodes.Deur_Scharnier1001.geometry} material={nodes.Deur_Scharnier1001.material} position={[0.447, 0.229, 0]} rotation={[Math.PI / 2, -0.809, 0]} scale={69.753} />
              </group>
              <mesh name="As2_Scharnier1001" geometry={nodes.As2_Scharnier1001.geometry} material={nodes.As2_Scharnier1001.material} rotation={[-Math.PI / 2, -1.448, -Math.PI]} scale={69.753} />
            </group>
          </group>
          <mesh name="Scharnier1_Fixed001" geometry={nodes.Scharnier1_Fixed001.geometry} material={nodes.Scharnier1_Fixed001.material} position={[0.018, 0.318, 0.582]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/objects/hinge.glb')
