/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 onderstel-og.glb --transform --keepnames 
Files: onderstel-og.glb [2.7KB] > /Users/joelmik/Code/kastenfabriek/public/objects/onderstel-og-transformed.glb [1.66KB] (39%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/objects/onderstel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Onderplaat001_ds_ws" geometry={nodes.Onderplaat001_ds_ws.geometry} material={nodes.Onderplaat001_ds_ws.material} position={[0, 0.1, 0]} />
    </group>
  )
}

useGLTF.preload('/objects/onderstel.glb')
