/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 9_WMSingle.glb -T -j -k 
Files: 9_WMSingle.glb [268.52KB] > /Users/joelmik/Code/kastenfabriek/public/objects/washermodules/9_WMSingle-transformed.glb [57.22KB] (79%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/9_WMSingle-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Wardrobe_Elements">
        <mesh name="DrawerRodFixedLeft001" geometry={nodes.DrawerRodFixedLeft001.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="DrawerRodFixedLeft002" geometry={nodes.DrawerRodFixedLeft002.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSinglePanel2Left" geometry={nodes.WMSinglePanel2Left.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSinglePanel1Left" geometry={nodes.WMSinglePanel1Left.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSinglePanel1Right" geometry={nodes.WMSinglePanel1Right.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSinglePanel2Right" geometry={nodes.WMSinglePanel2Right.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSingleFront" geometry={nodes.WMSingleFront.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSingleShelf1_ds" geometry={nodes.WMSingleShelf1_ds.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSingleShelf2_ds" geometry={nodes.WMSingleShelf2_ds.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSinglePanel3Right_ds" geometry={nodes.WMSinglePanel3Right_ds.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSinglePanel3Left_ds" geometry={nodes.WMSinglePanel3Left_ds.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSingleLeft1_ds" geometry={nodes.WMSingleLeft1_ds.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSingleBottom1_ds" geometry={nodes.WMSingleBottom1_ds.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSingleBack" geometry={nodes.WMSingleBack.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="WMSingleRight1_ds" geometry={nodes.WMSingleRight1_ds.geometry} material={materials['FrontColor.002']} position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]} />
        <group name="WMSingleMachineBack" position={[8.018, 0.136, 0.109]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Plane051" geometry={nodes.Plane051.geometry} material={materials['BaseMetal.001']} />
          <mesh name="Plane051_1" geometry={nodes.Plane051_1.geometry} material={materials['DryerControls.001']} />
          <mesh name="Plane051_2" geometry={nodes.Plane051_2.geometry} material={materials['Chrome.001']} />
          <mesh name="Plane051_3" geometry={nodes.Plane051_3.geometry} material={materials.DrumBump} />
          <mesh name="Plane051_4" geometry={nodes.Plane051_4.geometry} material={materials.DrumBump} />
          <mesh name="Plane051_5" geometry={nodes.Plane051_5.geometry} material={materials.Glass} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/9_WMSingle-transformed.glb')
