/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/objects/Handles-transformed.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Handles-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['24_Z0056'].geometry} material={nodes['24_Z0056'].material} position={[0, 0, -2.3]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['10_W7840'].geometry} material={nodes['10_W7840'].material} position={[0, 0, -0.9]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['5_W4080'].geometry} material={nodes['5_W4080'].material} position={[0, 0, -0.4]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['27_Z0056'].geometry} material={nodes['27_Z0056'].material} position={[0, 0, -2.6]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['7_W7822'].geometry} material={nodes['7_W7822'].material} position={[0, 0, -0.6]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['21_Z1080'].geometry} material={nodes['21_Z1080'].material} position={[0, 0, -2]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['14_W7870'].geometry} material={nodes['14_W7870'].material} position={[0, 0, -1.3]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['1_W4080'].geometry} material={nodes['1_W4080'].material} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['23_W7845'].geometry} material={nodes['23_W7845'].material} position={[0, 0, -2.2]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['22_Z7849'].geometry} material={nodes['22_Z7849'].material} position={[0, 0, -2.1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['20_Z1080'].geometry} material={nodes['20_Z1080'].material} position={[0, 0, -1.9]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['29_Z2168'].geometry} material={nodes['29_Z2168'].material} position={[0, 0, -2.8]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['9_W7840'].geometry} material={nodes['9_W7840'].material} position={[0, 0, -0.8]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['28_Z2168'].geometry} material={nodes['28_Z2168'].material} position={[0, 0, -2.7]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['11_W7840'].geometry} material={nodes['11_W7840'].material} position={[0, 0, -1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['2_W4080'].geometry} material={nodes['2_W4080'].material} position={[0, 0, -0.1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['13_W7870'].geometry} material={nodes['13_W7870'].material} position={[0, 0, -1.2]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['18_W7988'].geometry} material={nodes['18_W7988'].material} position={[0, 0, -1.7]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['4_W4080'].geometry} material={nodes['4_W4080'].material} position={[0, 0, -0.3]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['16_W7988'].geometry} material={nodes['16_W7988'].material} position={[0, 0, -1.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['3_W4080'].geometry} material={nodes['3_W4080'].material} position={[0, 0, -0.2]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['26_Z0056'].geometry} material={nodes['26_Z0056'].material} position={[0, 0, -2.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['8_W7822'].geometry} material={nodes['8_W7822'].material} position={[0, 0, -0.7]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['15_W7988'].geometry} material={nodes['15_W7988'].material} position={[0, 0, -1.4]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['25_Z0056'].geometry} material={nodes['25_Z0056'].material} position={[0, 0, -2.4]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['6_W4080'].geometry} material={nodes['6_W4080'].material} position={[0, 0, -0.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['12_W7871'].geometry} material={nodes['12_W7871'].material} position={[0, 0, -1.1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['19_Z1080'].geometry} material={nodes['19_Z1080'].material} position={[0, 0, -1.8]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['17_W7988'].geometry} material={nodes['17_W7988'].material} position={[0, 0, -1.6]} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/Handles-transformed.glb')
