/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Handles.glb -T -j -k
Files: Handles.glb [1.46MB] > /Users/joelmik/Code/kastenfabriek/public/objects/Handles-transformed.glb [164KB] (89%)

All handle meshes share rotation={[0, -Math.PI/2, 0]} — the -90° Y convention used by
all furniture GLBs in this project. After that rotation: local X → world Z (depth),
local Z → world X (width). Each product-code family contains multiple size variants laid
out along the GLB's local Z axis (= world X). All 29 size variants are individually
selectable; each is placed at [0,0,0] at the position supplied by the caller.

Mesh names follow the pattern `{numericId}_{productCode}`. The numeric ID uniquely
identifies each mesh; the product code appears on multiple size variants.

Multi-mesh handles (slice 056): when a handle is authored as multiple meshes that share
the same `{id}_` prefix, meshes whose name contains `knob` receive the customer-selected
metal material; remaining meshes receive a leather material derived from the handle's
`bodyColor`. Single-mesh handles (one node for a given id, or no `bodyColor`) keep the
original single-material path.
*/

import { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three/webgpu'
import {
  METALS,
  DEFAULT_HANDLE_MATERIAL,
  getLeather,
} from '../constants/handleMaterials'

export const HANDLE_TYPES = [
  { id: '1',  name: '1_W4080' },
  { id: '2',  name: '2_W4080' },
  { id: '3',  name: '3_W4080' },
  { id: '4',  name: '4_W4080' },
  { id: '5',  name: '5_W4080' },
  { id: '6',  name: '6_W4080' },
  { id: '7',  name: '7_W7822' },
  { id: '8',  name: '8_W7822' },
  { id: '9',  name: '9_W7840' },
  { id: '10', name: '10_W7840' },
  { id: '11', name: '11_W7840' },
  { id: '12', name: '12_W7871' },
  { id: '13', name: '13_W7870' },
  { id: '14', name: '14_W7870' },
  { id: '15', name: '15_W7988' },
  { id: '16', name: '16_W7988' },
  { id: '17', name: '17_W7988' },
  { id: '18', name: '18_W7988' },
  { id: '19', name: '19_Z1080' },
  { id: '20', name: '20_Z1080' },
  { id: '21', name: '21_Z1080' },
  { id: '22', name: '22_Z7849' },
  { id: '23', name: '23_W7845' },
  { id: '24', name: '24_Z0056' },
  { id: '25', name: '25_Z0056' },
  { id: '26', name: '26_Z0056' },
  { id: '27', name: '27_Z0056' },
  { id: '28', name: '28_Z2168' },
  { id: '29', name: '29_Z2168' },
  { id: '30', name: '30_H3121' },
  { id: '31', name: '31_H3161' },
]

const KNOB_NAME_REGEX = /Button/i

// Per-handle position tweaks for multi-mesh handles whose GLB authoring places them
// off the door surface or off-center. Coordinates are in metres, in the inner-group
// frame *before* the +π/2 Y rotation: x = lateral on door (mirrored automatically
// when mirror=true), y = vertical, z = outward from door surface (positive = out).
const MULTI_MESH_OFFSETS = {
  '30': [0, 0, -0.01],
  '31': [0.05, 0, -0.01],
}

// Per-handle position tweaks for single-mesh handles. Same coordinate frame as
// the multi-mesh offsets (after meshOffset centering, after the [0, π, 0] flip).
// x = lateral on door (mirrored automatically when mirror=true), y = vertical,
// z = outward from door surface. Default for handles not listed here is no shift.
const SINGLE_MESH_OFFSETS = {
  '1': [-0.06, 0, 0.02],
  '2': [-0.06, 0, 0.02],
  '3': [-0.06, 0, 0.02],
  '4': [-0.06, 0, 0.02],
  '5': [-0.06, 0, 0.02],
  '6': [-0.06, 0, 0.02],
  '7': [-0.06, 0, 0.02],
}

/**
 * @param {{
 *   id?: string,
 *   meshId?: string,
 *   mirror?: boolean,
 *   material?: import('../constants/handleMaterials').HandleMaterial,
 *   bodyColor?: import('../constants/handleMaterials').LeatherColor,
 *   [key: string]: any,
 * }} props
 */
export function HandleByType({
  id,
  meshId,
  mirror = false,
  material = DEFAULT_HANDLE_MATERIAL,
  bodyColor,
  ...props
}) {
  const { nodes } = useGLTF('/objects/Handles-transformed.glb')

  const lookupId = meshId ?? id

  const nodeKeys = useMemo(() => {
    if (!lookupId) return []
    return Object.keys(nodes).filter((k) => k.startsWith(`${lookupId}_`))
  }, [nodes, lookupId])

  const handleNodes = useMemo(() => {
    return nodeKeys
      .map((k) => nodes[k])
      .filter((n) => n && n.geometry)
  }, [nodes, nodeKeys])

  const materialMap = useMemo(() => {
    const map = {}
    for (const entry of METALS) {
      map[entry.id] = new THREE.MeshPhysicalMaterial(entry.pbr)
    }
    return map
  }, [])

  const activeMaterial = materialMap[material] ?? materialMap[DEFAULT_HANDLE_MATERIAL]

  const leatherMaterial = useMemo(() => {
    if (!bodyColor) return null
    const entry = getLeather(bodyColor)
    return new THREE.MeshStandardMaterial({
      color: entry.hex,
      metalness: 0.0,
      roughness: 0.7,
    })
  }, [bodyColor])

  const isMultiMesh = handleNodes.length > 1 && !!leatherMaterial

  // Offset the combined geometry so its back face (min z) sits at z=0 and x/y are
  // centered relative to the group, making the handle protrude outward from the
  // face it's placed on.
  // Multi-mesh handles share a common layout position in the GLB (e.g. handle 30's
  // body + button both sit at z=-2.9). Subtract the first node's position so the
  // pair is anchored at our group origin while preserving the small relative offset
  // between body and button.
  const multiMeshOrigin = useMemo(() => {
    if (!isMultiMesh) return null
    return handleNodes[0].position.clone()
  }, [handleNodes, isMultiMesh])

  const meshOffset = useMemo(() => {
    if (handleNodes.length === 0) return [0, 0, 0]
    const combined = new THREE.Box3()
    const tmp = new THREE.Box3()
    const m = new THREE.Matrix4()
    for (const n of handleNodes) {
      n.geometry.computeBoundingBox()
      if (!n.geometry.boundingBox) continue
      if (isMultiMesh) {
        const adjPos = n.position.clone().sub(multiMeshOrigin)
        m.compose(adjPos, n.quaternion, n.scale)
        // Compose with the extra -π/2 Y rotation applied to the multi-mesh group
        // so the offset centers the rotated geometry, not the unrotated one.
        const rot = new THREE.Matrix4().makeRotationY(Math.PI / 2)
        tmp.copy(n.geometry.boundingBox).applyMatrix4(m).applyMatrix4(rot)
        combined.union(tmp)
      } else {
        combined.union(n.geometry.boundingBox)
      }
    }
    if (combined.isEmpty()) return [0, 0, 0]
    const { min, max } = combined
    return [
      -(min.x + max.x) / 2,
      -(min.y + max.y) / 2,
      -min.z,
    ]
  }, [handleNodes, isMultiMesh, multiMeshOrigin])

  if (handleNodes.length === 0) return null

  return (
    <group {...props} scale={mirror ? [-1, 1, 1] : undefined}>
      <group position={meshOffset} rotation={[0, Math.PI, 0]}>
        {isMultiMesh
          ? (
            <group rotation={[0, Math.PI / 2, 0]} position={MULTI_MESH_OFFSETS[lookupId] ?? [0, 0, 0]}>
              {handleNodes.map((n, i) => {
                const isKnob = KNOB_NAME_REGEX.test(n.name ?? '')
                const adjPos = n.position.clone().sub(multiMeshOrigin)
                return (
                  <mesh
                    key={n.name ?? i}
                    geometry={n.geometry}
                    material={isKnob ? activeMaterial : leatherMaterial}
                    position={adjPos}
                    rotation={n.rotation}
                    scale={n.scale}
                  />
                )
              })}
            </group>
          )
          : (
            <group position={SINGLE_MESH_OFFSETS[lookupId] ?? [0, 0, 0]}>
              <mesh
                geometry={handleNodes[0].geometry}
                material={activeMaterial}
              />
            </group>
          )}
      </group>
    </group>
  )
}

useGLTF.preload('/objects/Handles-transformed.glb')
