/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Handles.glb -T -j -k
Files: Handles.glb [1.46MB] > /Users/joelmik/Code/kastenfabriek/public/objects/Handles-transformed.glb [164KB] (89%)

All handle meshes share rotation={[0, -Math.PI/2, 0]} — the -90° Y convention used by
all furniture GLBs in this project. After that rotation: local X → world Z (depth),
local Z → world X (width). Each product-code family contains multiple size variants laid
out along the GLB's local Z axis (= world X). All 29 size variants are individually
selectable; each is placed at [0,0,0] at the position supplied by the caller.

Mesh names follow the pattern `{numericId}_{productCode}`. The numeric ID uniquely
identifies each mesh; the product code appears on multiple size variants.
*/

import { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three/webgpu'
import { METALS, DEFAULT_HANDLE_MATERIAL } from '../constants/handleMaterials'

export const HANDLE_TYPES = [
  { id: '1',  name: '1_W4080' },
  { id: '2',  name: '2_W4080' },
  { id: '3',  name: '3_W4080' },
  { id: '4',  name: '4_W4080' },
  { id: '5',  name: '5_W4080' },
  { id: '6',  name: '6_W4080' },
  { id: '7',  name: '7_W7822' },
  { id: '8',  name: '8_W7822' },
  { id: '9',  name: '9_W7840' },
  { id: '10', name: '10_W7840' },
  { id: '11', name: '11_W7840' },
  { id: '12', name: '12_W7871' },
  { id: '13', name: '13_W7870' },
  { id: '14', name: '14_W7870' },
  { id: '15', name: '15_W7988' },
  { id: '16', name: '16_W7988' },
  { id: '17', name: '17_W7988' },
  { id: '18', name: '18_W7988' },
  { id: '19', name: '19_Z1080' },
  { id: '20', name: '20_Z1080' },
  { id: '21', name: '21_Z1080' },
  { id: '22', name: '22_Z7849' },
  { id: '23', name: '23_W7845' },
  { id: '24', name: '24_Z0056' },
  { id: '25', name: '25_Z0056' },
  { id: '26', name: '26_Z0056' },
  { id: '27', name: '27_Z0056' },
  { id: '28', name: '28_Z2168' },
  { id: '29', name: '29_Z2168' },
]

export function HandleByType({ id, mirror = false, material = DEFAULT_HANDLE_MATERIAL, ...props }) {
  const { nodes } = useGLTF('/objects/Handles-transformed.glb')

  const nodeKey = id ? Object.keys(nodes).find((k) => k.startsWith(`${id}_`)) : null
  const node = nodeKey ? nodes[nodeKey] : null

  const materialMap = useMemo(() => {
    const map = {}
    for (const entry of METALS) {
      map[entry.id] = new THREE.MeshPhysicalMaterial(entry.pbr)
    }
    return map
  }, [])

  const activeMaterial = materialMap[material] ?? materialMap[DEFAULT_HANDLE_MATERIAL]

  // Offset the mesh so its back face (min z) sits at z=0 relative to the group,
  // making the handle protrude outward from whichever face the group is placed on.
  // Also centers x and y so placement position is the visual center of the handle.
  const meshOffset = useMemo(() => {
    if (!node?.geometry) return [0, 0, 0]
    const geo = node.geometry
    geo.computeBoundingBox()
    if (!geo.boundingBox) return [0, 0, 0]
    const { min, max } = geo.boundingBox
    return [
      -(min.x + max.x) / 2,
      -(min.y + max.y) / 2,
      -min.z,
    ]
  }, [node])

  if (!node) return null

  return (
    <group {...props} scale={mirror ? [-1, 1, 1] : undefined}>
      <mesh geometry={node.geometry} material={activeMaterial} position={meshOffset} rotation={[0, Math.PI, 0]} />
    </group>
  )
}

useGLTF.preload('/objects/Handles-transformed.glb')
