/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hinge-og.glb -T -j -k
Files: hinge-og.glb [33.6KB] > /Users/joelmik/Code/kastenfabriek/public/objects/hinge-og-transformed.glb [25.95KB] (23%)
*/

import { useRef, useEffect, useMemo } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three/webgpu'
import gsap from 'gsap'

export function Model({ doorsOpen = false, ...props }) {
  const group = useRef()
  const proxyRef = useRef({ t: 0 })
  const { nodes, animations, scene } = useGLTF('/objects/HingeNewt.glb')
  const { actions } = useAnimations(animations, group)

  // Center the hinge model at origin so position prop places it correctly
  const offset = useMemo(() => {
    const box = new THREE.Box3().setFromObject(scene)
    return box.getCenter(new THREE.Vector3()).negate()
  }, [scene])


  const chromeMaterial = useMemo(() => {
    return new THREE.MeshPhysicalMaterial({
      color: 0xd3d3d3,
      metalness: 0.9,
      roughness: 0.2,
      envMapIntensity: 2,
      clearcoat: 1,
      clearcoatRoughness: 0,
    })
  }, [])

  // Initialize: play once and immediately pause at t=0
  useEffect(() => {
    const action = Object.values(actions)[0]
    if (!action) return
    action.reset()
    action.play()
    action.paused = true
    action.time = 0
    proxyRef.current.t = 0
  }, [actions])

  // Animate action.time based on doorsOpen
  useEffect(() => {
    const action = Object.values(actions)[0]
    if (!action) return
    const duration = action.getClip().duration

    gsap.killTweensOf(proxyRef.current)
    gsap.to(proxyRef.current, {
      t: doorsOpen ? duration : 0,
      duration: 0.6,
      ease: 'power2.inOut',
      onUpdate: () => {
        action.time = Math.max(0, Math.min(duration, proxyRef.current.t))
      },
    })
  }, [doorsOpen, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[offset.x, offset.y, offset.z]}>
        <group name="Wardrobe_Elements">
          <mesh name="Scharnier1_Fixed" geometry={nodes.Scharnier1_Fixed.geometry} material={chromeMaterial} position={[0.018, 0.318, 0.582]} />
          <mesh name="As1_Scharnier1" geometry={nodes.As1_Scharnier1.geometry} material={chromeMaterial} position={[0.026, 0.318, 0.577]} />
          <mesh name="Deur_Scharnier1" geometry={nodes.Deur_Scharnier1.geometry} material={chromeMaterial} position={[0.018, 0.318, 0.582]} />
          <mesh name="As2_Scharnier1" geometry={nodes.As2_Scharnier1.geometry} material={chromeMaterial} position={[0.036, 0.318, 0.586]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/objects/HingeNewt.glb')
