/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 31_ModuleSplit.glb -T -j -k 
Files: 31_ModuleSplit.glb [86.34KB] > /Users/joelmik/Code/kastenfabriek/public/objects/31_ModuleSplit-transformed.glb [13.67KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/31_ModuleSplit-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="SplitRod_ws" geometry={nodes.SplitRod_ws.geometry} material={nodes.SplitRod_ws.material} position={[4.018, 0.136, 0.03]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="SplitMiddle_ds" geometry={nodes.SplitMiddle_ds.geometry} material={nodes.SplitMiddle_ds.material} position={[4.018, 0.136, 0.03]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="SplitShelf_ds_ws" geometry={nodes.SplitShelf_ds_ws.geometry} material={nodes.SplitShelf_ds_ws.material} position={[4.018, 0.136, 0.03]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="SplitShelfTop_ds_ws" geometry={nodes.SplitShelfTop_ds_ws.geometry} material={nodes.SplitShelfTop_ds_ws.material} position={[4.018, 0.136, 0.03]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="SplitFixedMiddle" geometry={nodes.SplitFixedMiddle.geometry} material={nodes.SplitFixedMiddle.material} position={[4.018, 0.136, 0.03]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="SplitFixedRight" geometry={nodes.SplitFixedRight.geometry} material={nodes.SplitFixedRight.material} position={[4.018, 0.136, 0.03]} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/31_ModuleSplit-transformed.glb')
