/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 37_Hanger1.glb -T -j -k 
Files: 37_Hanger1.glb [316.75KB] > /Users/joelmik/Code/kastenfabriek/public/objects/37_Hanger1-transformed.glb [175.92KB] (44%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/37_Hanger1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Hanger" position={[2.018, 0.136, 0.03]}>
        <mesh name="Hi_Remesh2" geometry={nodes.Hi_Remesh2.geometry} material={materials['Material9616.003']} />
        <mesh name="Hi_Remesh2_1" geometry={nodes.Hi_Remesh2_1.geometry} material={materials['Material9620.003']} />
        <mesh name="Hi_Remesh2_2" geometry={nodes.Hi_Remesh2_2.geometry} material={materials.Collar} />
        <mesh name="Hi_Remesh2_3" geometry={nodes.Hi_Remesh2_3.geometry} material={materials.Body} />
        <mesh name="Hi_Remesh2_4" geometry={nodes.Hi_Remesh2_4.geometry} material={materials.Labels} />
      </group>
    </group>
  )
}

useGLTF.preload('/37_Hanger1-transformed.glb')
