/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Handles.glb -T -j -k 
Files: Handles.glb [1.49MB] > /Users/joelmik/Code/kastenfabriek/public/objects/Handles-transformed.glb [169.81KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Handles-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="24_Z0056" geometry={nodes['24_Z0056'].geometry} material={nodes['24_Z0056'].material} position={[0, 0, -2.3]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="10_W7840" geometry={nodes['10_W7840'].geometry} material={nodes['10_W7840'].material} position={[0, 0, -0.9]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="5_W4080" geometry={nodes['5_W4080'].geometry} material={nodes['5_W4080'].material} position={[0, 0, -0.4]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="27_Z0056" geometry={nodes['27_Z0056'].geometry} material={nodes['27_Z0056'].material} position={[0, 0, -2.6]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="7_W7822" geometry={nodes['7_W7822'].geometry} material={nodes['7_W7822'].material} position={[0, 0, -0.6]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="21_Z1080" geometry={nodes['21_Z1080'].geometry} material={nodes['21_Z1080'].material} position={[0, 0, -2]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="14_W7870" geometry={nodes['14_W7870'].geometry} material={nodes['14_W7870'].material} position={[0, 0, -1.3]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="1_W4080" geometry={nodes['1_W4080'].geometry} material={nodes['1_W4080'].material} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="23_W7845" geometry={nodes['23_W7845'].geometry} material={nodes['23_W7845'].material} position={[0, 0, -2.2]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="22_Z7849" geometry={nodes['22_Z7849'].geometry} material={nodes['22_Z7849'].material} position={[0, 0, -2.1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="20_Z1080" geometry={nodes['20_Z1080'].geometry} material={nodes['20_Z1080'].material} position={[0, 0, -1.9]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="29_Z2168" geometry={nodes['29_Z2168'].geometry} material={nodes['29_Z2168'].material} position={[0, 0, -2.8]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="9_W7840" geometry={nodes['9_W7840'].geometry} material={nodes['9_W7840'].material} position={[0, 0, -0.8]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="28_Z2168" geometry={nodes['28_Z2168'].geometry} material={nodes['28_Z2168'].material} position={[0, 0, -2.7]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="11_W7840" geometry={nodes['11_W7840'].geometry} material={nodes['11_W7840'].material} position={[0, 0, -1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="2_W4080" geometry={nodes['2_W4080'].geometry} material={nodes['2_W4080'].material} position={[0, 0, -0.1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="13_W7870" geometry={nodes['13_W7870'].geometry} material={nodes['13_W7870'].material} position={[0, 0, -1.2]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="18_W7988" geometry={nodes['18_W7988'].geometry} material={nodes['18_W7988'].material} position={[0, 0, -1.7]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="4_W4080" geometry={nodes['4_W4080'].geometry} material={nodes['4_W4080'].material} position={[0, 0, -0.3]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="16_W7988" geometry={nodes['16_W7988'].geometry} material={nodes['16_W7988'].material} position={[0, 0, -1.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="3_W4080" geometry={nodes['3_W4080'].geometry} material={nodes['3_W4080'].material} position={[0, 0, -0.2]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="26_Z0056" geometry={nodes['26_Z0056'].geometry} material={nodes['26_Z0056'].material} position={[0, 0, -2.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="8_W7822" geometry={nodes['8_W7822'].geometry} material={nodes['8_W7822'].material} position={[0, 0, -0.7]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="15_W7988" geometry={nodes['15_W7988'].geometry} material={nodes['15_W7988'].material} position={[0, 0, -1.4]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="25_Z0056" geometry={nodes['25_Z0056'].geometry} material={nodes['25_Z0056'].material} position={[0, 0, -2.4]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="6_W4080" geometry={nodes['6_W4080'].geometry} material={nodes['6_W4080'].material} position={[0, 0, -0.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="12_W7871" geometry={nodes['12_W7871'].geometry} material={nodes['12_W7871'].material} position={[0, 0, -1.1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="19_Z1080" geometry={nodes['19_Z1080'].geometry} material={nodes['19_Z1080'].material} position={[0, 0, -1.8]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="17_W7988" geometry={nodes['17_W7988'].geometry} material={nodes['17_W7988'].material} position={[0, 0, -1.6]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="31_H3161" geometry={nodes['31_H3161'].geometry} material={nodes['31_H3161'].material} position={[0, 0, -3]} />
      <mesh name="30_H3121" geometry={nodes['30_H3121'].geometry} material={nodes['30_H3121'].material} position={[0, 0, -2.9]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="31_H3161_Button" geometry={nodes['31_H3161_Button'].geometry} material={nodes['31_H3161_Button'].material} position={[0, 0, -3]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="30_H3121_Button" geometry={nodes['30_H3121_Button'].geometry} material={nodes['30_H3121_Button'].material} position={[0.008, 0, -2.9]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.02, 1]} />
    </group>
  )
}

useGLTF.preload('/Handles-transformed.glb')
