/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ladesbinnen-og.glb --transform --keepnames 
Files: ladesbinnen-og.glb [4.2KB] > /Users/joelmik/Code/kastenfabriek/public/objects/ladesbinnen-og-transformed.glb [3.06KB] (27%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ladesbinnen-og-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="lades_ws" geometry={nodes.lades_ws.geometry} material={nodes.lades_ws.material} position={[0.035, 0.018, -0.009]} rotation={[0, -1.571, 0]} />
      <mesh name="ladesPlank_ds" geometry={nodes.ladesPlank_ds.geometry} material={materials.Kast_Mat} position={[0.035, 0.018, -0.009]} rotation={[0, -1.571, 0]} />
    </group>
  )
}

useGLTF.preload('/ladesbinnen-og-transformed.glb')
