/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ladesbinnen-og.glb --transform --keepnames 
Files: ladesbinnen-og.glb [187.94KB] > /Users/joelmik/Code/kastenfabriek/public/objects/ladesbinnen-og-transformed.glb [98.66KB] (48%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ladesbinnen-og-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="LadeZijpaneel3004_ds" geometry={nodes.LadeZijpaneel3004_ds.geometry} material={nodes.LadeZijpaneel3004_ds.material} position={[3.018, 0.136, 0.03]} rotation={[0, -1.571, 0]} />
    </group>
  )
}

useGLTF.preload('/ladesbinnen-og-transformed.glb')
