/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 modulesog.glb --transform --keepnames 
Files: modulesog.glb [1.32MB] > /Users/joelmik/Code/kastenfabriek/public/objects/modulesog-transformed.glb [288.26KB] (78%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/modulesog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Module1" geometry={nodes.Module1.geometry} material={materials.PaletteMaterial001} position={[0.652, 1.018, -0.258]} rotation={[0, -1.571, 0]} />
      <mesh name="Module2" geometry={nodes.Module2.geometry} material={materials.PaletteMaterial002} position={[2.952, 2.018, -0.274]} rotation={[0, -1.571, 0]} />
      <mesh name="Ruimte" geometry={nodes.Ruimte.geometry} material={materials.Poliigon_WoodFloorChevron_9783_1K} position={[4.361, -0.1, 1.298]} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/modulesog-transformed.glb')
