/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 modules-og.glb --transform --keepnames 
Files: modules-og.glb [111.52KB] > /Users/joelmik/Code/kastenfabriek/public/objects/modules-og-transformed.glb [6.56KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/modules-og-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Ruimte" geometry={nodes.Ruimte.geometry} material={materials.Muur} position={[4.361, -0.1, 0.308]} rotation={[0, -Math.PI / 2, 0]} scale={[1.593, 1, 7.088]} />
      <mesh name="Module1" geometry={nodes.Module1.geometry} material={materials.Kast_Mat_Wit} position={[0.652, 1.018, -0.258]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="Module2" geometry={nodes.Module2.geometry} material={materials.Metal} position={[2.952, 2.018, -0.274]} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/modules-og-transformed.glb')
