/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 module1-og.glb --transform --keepnames 
Files: module1-og.glb [12.25KB] > /Users/joelmik/Code/kastenfabriek/public/objects/module1-og-transformed.glb [3.67KB] (70%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/module1-og-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Staander_R" geometry={nodes.Staander_R.geometry} material={materials.Wit_Glim} position={[11, 0, -17.573]} />
      <mesh name="Deur" geometry={nodes.Deur.geometry} material={materials['Kast_Mat.002']} position={[11.582, 0.002, -16.993]} />
    </group>
  )
}

useGLTF.preload('/module1-og-transformed.glb')
