/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 modulesog.glb --transform --keepnames 
Files: modulesog.glb [1.32MB] > /Users/joelmik/Code/kastenfabriek/public/objects/modulesog-transformed.glb [289.34KB] (78%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/modulesog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Module1" position={[0.652, 1.018, -0.258]} rotation={[0, -1.571, 0]}>
        <mesh name="Cube437" geometry={nodes.Cube437.geometry} material={materials.Kast_Mat_Wit} />
        <mesh name="Cube437_1" geometry={nodes.Cube437_1.geometry} material={materials['Black ']} />
      </group>
      <mesh name="Module2" geometry={nodes.Module2.geometry} material={materials.Metal} position={[2.952, 2.018, -0.274]} rotation={[0, -1.571, 0]} />
      <group name="Ruimte" position={[4.361, -0.1, 1.298]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.Muur} />
        <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials.Poliigon_WoodFloorChevron_9783_1K} />
      </group>
    </group>
  )
}

useGLTF.preload('/modulesog-transformed.glb')
