/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 module6-og.glb --transform --keepnames 
Files: module6-og.glb [12.4KB] > /Users/joelmik/Code/kastenfabriek/public/objects/module6-og-transformed.glb [3.78KB] (70%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/module6-og-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Staander_R" geometry={nodes.Staander_R.geometry} material={materials.Wit_Glim} position={[0.573, 0, -0.009]} />
      <mesh name="Deur" geometry={nodes.Deur.geometry} material={materials['Kast_Mat.002']} position={[-0.007, 0.002, 0.573]} />
    </group>
  )
}

useGLTF.preload('/module6-og-transformed.glb')
